services:
  - type: web
    name: inventaire-pro
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER_DISK_PATH
        value: /opt/render/project/src/backend/data
    disk:
      name: inventaire-data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1
